#!/bin/sh

[ -f "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Wallpaper changed." &

[ -d "$1" ] && cp "$(find "$1"/ -name *.jpg -o -name *.png -o -name *.jpeg -type f | shuf -n 1)" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Random wallpaper chosen."

# use pywal to generate the color scheme, check if installed
#type wal >/dev/null 2>&1 && { wal -c
	#wal -s -i ~/.config/wall.png -o ~/.config/wal/postrun
#	wal -i ~/.config/wall.png -o ~/.config/wal/postrun
	#xsetroot -name "fsignal:xrdb"
	#killall dwmblocks
	#setsid dwmblocks >/dev/null & } >/dev/null 2>&1


status &
xwallpaper --zoom ~/.config/wall.png
#xrdb ~/.config/.Xresources
